import Head from 'next/head'
import Image from 'next/image'
import Header from '../Component/Header/Header'
import NavBar from '../Component/Nav/NavBar'
import styles from '../styles/Home.module.css'
import Acceleration from '../Component/Acceleration/Acceleration'
import Customer from '../Component/Customer/Customer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Klenty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <NavBar/>
      <Header/>
      <Acceleration/>
      <Customer/> 
    </div>
  )
}
